
function ekarriGaldera(){
	//......1
	var galdesorta = 
	{"galderak":	   
	[{"galdera":"¡Qué alegría le hemos dado!", 
	"auke1":"Hori poza eman dioguna!","auke2":"Poza handia eman diogula!","auke3":"Nolako poza eman diogula!",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Hori poza eman dioguna!\n-A zer (nolako) poza eman diogun! ere zuzena da.",
	"eranfb2":"Ez da zuzena.\n-Hori poza eman dioguna! eta \n-A zer (nolako) poza eman diogun! dira zuzenak",
	"eranfb3":"Ez da zuzena.\n-Hori poza eman dioguna! eta \n-A zer (nolako) poza eman diogun! dira zuzenak"	},
		//......2
	{"galdera":"¡Qué casa tan hermosa!",
	"auke1":"Etxea hain polita da!","auke2":"Polita dela etxea!","auke3":"Zeinen etxe polita!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n-Zeinen etxe polita!-, \n-Hau etxe polita! eta \n-Bai etxe polita!- dira zuzenak",
	"eranfb2":"Ez da zuzena.\n-Zeinen etxe polita!-, -Hau etxe polita! eta -Bai etxe polita!- dira zuzenak",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Zeinen etxe polita! \n-Hau etxe polita! eta \n-Bai etxe polita! ere zuzenak dira."},
		//......3
	{"galdera":"¡Qué disgusto les voy a dar!",
	"auke1":"Disgustoa emango diedala!","auke2":"Hori disgustoa emango diedana!","auke3":"Emango diedala disgustoa!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n-Hori disgustoa emango diedana! da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Hori disgustoa emango diedana!",
	"eranfb3":"Ez da zuzena.\n-Hori disgustoa emango diedana! da zuzena."},
		//......4
	{"galdera":"¡Qué manos más bonitas tienes!",
	"auke1":"Nolako esku politagoak dituzun!","auke2":"Zer esku gehiago politak dituzula!","auke3":"Zeinen esku politak dituzun!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Zeinen esku politak dituzun-,\n-Bai esku politak dituzula- eta \n–Horiek esku politak dituzunak- dira zuzenak.",
	"eranfb2":"Ez da zuzena.\n–Zeinen esku politak dituzun-,\n-Bai esku politak dituzula- eta \n–Horiek esku politak dituzunak- dira zuzenak.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Bai esku politak dituzula- eta \n–Horiek esku politak dituzunak- ere zuzenak dira."},
		//......5
	{"galdera":"¡Vosotros sí que estáis locos!",
	"auke1":"Zuek eroak zaretela bai!","auke2":"Zuek bai zaudetela erotuta!","auke3":"Zuek bai zaudete eroak!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Zuek bai zaudetela erotuta da zuzena.",
	"eranfb2":" Bai, hori da erantzun zuzena:\n-Zuek bai zaudetela erotuta!",
	"eranfb3":" Ez da zuzena.\n–Zuek bai zaudetela erotuta da zuzena. "},
		//......6
	{"galdera":"¡Tenía que ser precisamente mañana!",
	"auke1":"Noiz eta bihar izan behar!","auke2":" Izan behar zuela prezeski bihar!","auke3":"Izan behar zuen bihar!",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\nNoiz eta bihar izan behar!\n-Noiz izango eta bihar! ere zuzena da. ",
	"eranfb2":"Ez da zuzena.\n–Noiz eta bihar izan behar. eta -Noiz izango eta bihar. dira zuzenak.",
	"eranfb3":"Ez da zuzena.\n–Noiz eta bihar izan behar. eta -Noiz izango eta bihar. dira zuzenak. "},
	//......7
	{"galdera":"¡Qué contento estoy!",
	"auke1":"Nagoela oso pozik!","auke2":"Bai pozik nagoela!","auke3":"Nolako pozik nagoen!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Bai pozik nagoela! da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Bai pozik nagoela!",
	"eranfb3":"Ez da zuzena.\n–Bai pozik nagoela! da zuzena."},
	//......8
	{"galdera":"¡Menos mal que no se lo has dicho!",
	"auke1":"Eskerrak ez diozula esan!","auke2":" Gutxi gaizki ez diozula esan!","auke3":"Gaizki gutxiago ez diozun esan!",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Eskerrak ez diozula esan!",
	"eranfb2":"Ez da zuzena.\n–Eskerrak ez diozula esan! da zuzena.",
	"eranfb3":"Ez da zuzena.\n–Eskerrak ez diozula esan! da zuzena."},
		//......9
	{"galdera":"¡Imagínate la rabia que me ha dado!",
	"auke1":"Irudikatu amorrua eman didana!","auke2":" Imaginatu amorrua eman didala!","auke3":"Pentsa nolako amorrua eman didan!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Pentsa nolako amorrua eman didan! da zuzena.",
	"eranfb2":"Ez da zuzena.\n–Pentsa nolako amorrua eman didan! da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Pentsa nolako amorrua eman didan!"},
		//......10
	{"galdera":"¡Lo vuestro no tiene remedio!",
	"auke1":"Ez duzue erremediorik!","auke2":"Zuenak ez du erremediorik!","auke3":"Zuenak erremedioa ez dauka!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Zuenak ez du erremediorik! da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Zuenak ez du erremediorik!",
	"eranfb3":"Ez da zuzena.\n–Zuenak ez du erremediorik! da zuzena. "},
	//......11
	{"galdera":"¡Vete a saber qué estará haciendo a estas horas!",
	"auke1":"Joan jakitera zer egiten ari den orduotan!","auke2":" Jakin ezazu zer egiten ari den orduotan!","auke3":"Auskalo zertan dabilen ordu hauetan!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Auskalo zertan dabilen ordu hauetan! da zuzena.",
	"eranfb2":"Ez da zuzena.\n–Auskalo zertan dabilen ordu hauetan! da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Auskalo zertan dabilen ordu hauetan!"},
		//......12
	{"galdera":"¡Mira lo que ocurre si no se tiene cuidado!",
	"auke1":"Horra hor zer gertatzen den, kontuz ibili ezean!","auke2":"Begiratu gertatzen dena, ez baduzu konturik!","auke3":"Begiratu zer gertatzen den, kontuz ibili ezean!",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Horra hor zer gertatzen den, kontuz ibili ezean!",
	"eranfb2":"Ez da zuzena.\n–Horra hor zer gertatzen den, kontuz ibili ezean! da zuzena.",
	"eranfb3":"Ez da zuzena.\n–Horra hor zer gertatzen den, kontuz ibili ezean! da zuzena."},
		//......13
	{"galdera":"¡Ójala nieve!",
	"auke1":"Egitea elurra!","auke2":"Elurra egingo ahal du!","auke3":"Elurra egitea!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Elurra egingo ahal du! da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Elurra egingo ahal du!",
	"eranfb3":"Ez da zuzena.\n–Elurra egingo ahal du! da zuzena."},
		//......14
	{"galdera":"¡Qué pronto te cansas!",
	"auke1":"Bai azkar nekatzen zarela!","auke2":"Nekatzen zarela super azkar!","auke3":"Oso azkar nekatzen zara!",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Bai azkar nekatzen zarela!",
	"eranfb2":"Ez da zuzena.\n–Bai azkar nekatzen zarela! da zuzena.",
	"eranfb3":"Ez da zuzena.\n–Bai azkar nekatzen zarela! da zuzena."},
		//......15
	{"galdera":"!A que no llegas a tiempo!",
	"auke1":"Ez zarela iristen garaiz!","auke2":"Ez iritsiko zara garaiz!","auke3":"Ezetz garaiz iritsi!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Ezetz garaiz iritsi! da zuzena.",
	"eranfb2":"Ez da zuzena.\n–Ezetz garaiz iritsi! da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Ezetz garaiz iritsi!"},
		//......16
	{"galdera":"¡Qué zapatos más caros!",
	"auke1":"Zapatak oso garestiak direla!","auke2":"Zer zapata garestiagoak!","auke3":"Horiek zapata garestiak!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Horiek zapata garestiak! da zuzena.",
	"eranfb2":"Ez da zuzena.\n–Horiek zapata garestiak! da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Horiek zapata garestiak!"},
		//......17
	{"galdera":"¡Qué pelo más largo tienes!",
	"auke1":"Zer ile luzeagoa daukazula!","auke2":"Hori ile luzea daukazuna!","auke3":"Zer ile oso luzea daukazula!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Hori ile luzea daukazuna!\n-Bai ile luzea daukazula! eta \n–Zeinen ile luzea daukazun! dira zuzenak.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Hori ile luzea daukazuna!\n-Bai ile luzea daukazula! eta \n–Zeinen ile luzea daukazun! ere zuzenak dira.",
	"eranfb3":"Ez da zuzena.\n–Hori ile luzea daukazuna!\n-Bai ile luzea daukazula! eta \n–Zeinen ile luzea daukazun! dira zuzenak."},
	//......18
	{"galdera":"¡Qué vida más dura!",
	"auke1":"Zer bizitza gogorra den!","auke2":"Gogorra bizitza!","auke3":"Zer bizitza gogorragoa!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Gogorra bizitza! da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Gogorra bizitza!",
	"eranfb3":"Ez da zuzena.\n–Gogorra bizitza! da zuzena."},
		//......19
	{"galdera":"!Cuánto habla ese tipo!",
	"auke1":"Zenbat hitz egiten du tipo horrek!","auke2":"Zenbat hitz egiten duen morroi horrek!","auke3":"Asko hitz egiten du horrek!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Zenbat hitz egiten duen morroi horrek! da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Zenbat hitz egiten duen morroi horrek!",
	"eranfb3":"Ez da zuzena.\n–Zenbat hitz egiten duen morroi horrek! da zuzena."},
		//......20
	{"galdera":"¡Qué miedo he pasado cuando me ha mirado!",
	"auke1":"Nolako beldurra pasatu zait begiratu didanean!","auke2":"Hori beldurra pasa dudana begiratu didanean!","auke3":"Nolako beldurra pasa dut begiratu didanean!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Hori beldurra pasa dudana begiratu didanean! da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n–Hori beldurra pasa dudana begiratu didanean!",
	"eranfb3":"Ez da zuzena.\n–Hori beldurra pasa dudana begiratu didanean! da zuzena."},
		//......21
	{"galdera":"¡Menudas preguntas haces!",
	"auke1":"Nolako galderak egiten dituzu!","auke2":"A zer galderak egiten dituzun!","auke3":"Galdera txikiak egiten dituzula!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–A zer galderak egiten dituzun! da zuzena.\nBaita -Horiek galderak egiten dituzunak! ere.",
	"eranfb2":"Bai, hori da erantzun zuzena: \n–A zer galderak egiten dituzun! \n-Horiek galderak egiten dituzunak! ere zuzena da.",
	"eranfb3":"Ez da zuzena.\n–A zer galderak egiten dituzun!– da zuzena.\nBaita -Horiek galderak egiten dituzunak! ere."},
		//......22
	{"galdera":"¡Menos mal que has llegado a tiempo! ",
	"auke1":"Gaitz gutxiago garaiz iritsi zaren!","auke2":"Eskerrak garaiz iritsi zaren!","auke3":"Eskerrak denborara iritsi zarelako!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Eskerrak garaiz iritsi zaren edo zarena edo zarela! da zuzena. Gainera -gaitz gutxiago- formak ez dauka ez buru ez hankarik esaldi horretan.",
	"eranfb2":"Bai, hori da erantzun zuzena: \n-Eskerrak garaiz iritsi zaren edo zarena edo zarela!.",
	"eranfb3":"Ez da zuzena.\n–Eskerrak garaiz iritsi zaren edo zarena edo zarela! da zuzena. -denborara-????"},
		//......23
	{"galdera":"¡Qué guapo estás callado!",
	"auke1":"Zein polita zauden isilik!","auke2":"Zer polita zaudela isilik! ","auke3":"Zer polita zaude isilik! ",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Zein polita zauden isilik!\n-Bai polita zaudela isilik! ere zuzena da. ",
	"eranfb2":"Ez da zuzena.\n-Zein polita zauden isilik! da zuzena.\n-Bai polita zaudela isilik! ere zuzena da.",
	"eranfb3":"Ez da zuzena.\n -Zein polita zauden isilik! da zuzena.\n-Bai polita zaudela isilik! ere zuzena da."},
		//......24
	{"galdera":" ¡Ojalá no lleguen a la cima!",
	"auke1":"Ez daitezela tontorrera iritsi!","auke2":"Nahi dut tontorrera ez iritsi haiek!","auke3":"Ez ahal dira tontorrera iritsiko!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n-Ez ahal dira tontorrera iritsiko! da zuzena.",
	"eranfb2":"Ez da zuzena.\n-Ez ahal dira tontorrera iritsiko! da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Ez ahal dira tontorrera iritsiko!"},
		//......25
	{"galdera":"¡Por supuesto que iré! ",
	"auke1":"Zapatak oso garestiak direla!","auke2":"Zer zapata garestiagoak!","auke3":"Horixe joango naizela!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena. \nHorixe joango naizela! da zuzena.\n-Jakina, joango ez naiz bada! ere zuzena da. ",
	"eranfb2":"Ez da zuzena. \nHorixe joango naizela! da zuzena.\n-Jakina, joango ez naiz bada! ere zuzena da. ",
	"eranfb3":"Bai, hori da erantzun zuzena:\nHorixe joango naizela!\n-Jakina, joango ez naiz bada! ere zuzena da."},
		//......26
	{"galdera":" ¡Cómo no le voy a creer, si es mi amigo!",
	"auke1":"Nola ez nik sinetsi, nire laguna bada!","auke2":"Nola ez diot ba sinetsiko, nire laguna bada!","auke3":"Nola ez joan sinistera, bada nire laguna!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n-Nola ez diot ba sinetsiko, nire laguna bada! da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Nola ez diot ba sinetsiko, nire laguna bada!",
	"eranfb3":"Ez da zuzena.\n-Nola ez diot ba sinetsiko, nire laguna bada! da zuzena."},
			//......27
	{"galdera":" ¡Mira quién viene! ",
	"auke1":"Ikusi nor dator!","auke2":"Hara nor datorren!","auke3":"Begiratu nor dator!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n-Hara nor datorren! da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena: \n-Hara nor datorren!",
	"eranfb3":"Ez da zuzena.\n-Hara nor datorren! da zuzena."},
		//......23
	{"galdera":" ¡Tú precisamente tenías que ser!",
	"auke1":"Nor izango eta zu!","auke2":"Zu izan behar zinen! ","auke3":"Prezeski zu zarela! ",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena.\n-Nor izango eta zu!.\n-Nork eta zuk izan behar! ere zuzena da. ",
	"eranfb2":"Ez da zuzena.\n-Nor izango eta zu! da zuzena.\n-Nork eta zuk izan behar! ere zuzena da.",
	"eranfb3":"Ez da zuzena.\n-Nor izango eta zu! da zuzena.\n-Nork eta zuk izan behar! ere zuzena da."},
		//......28
	{"galdera":" ¡Gracias que ha hecho buen tiempo; si no, dónde nos habríamos metido!",
	"auke1":"Eskerrik asko eguraldi ona egin du, ez bada, non sartuko ginatekeen!","auke2":"Eskerrak zer eguraldi ona egin du, ez bada non sartuko ginen!","auke3":"Eskerrak eguraldi ona egin duen, bestela non sartuko ginen!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n-Eskerrak eguraldi ona egin duen (edo duena edo duela), bestela non sartuko ginen! da zuzena.",
	"eranfb2":"Ez da zuzena.\n-Eskerrak eguraldi ona egin duen (edo duena edo duela), bestela non sartuko ginen! da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Eskerrak eguraldi ona egin duen (edo duena edo duela), bestela non sartuko ginen!"},
		//......29
	{"galdera":" ¡A que no sabes quién ha llamado! ",
	"auke1":"Ez duzu jakin nork deitu du!","auke2":"Zera ez dakizu nork deitu du!","auke3":"Ezetz asmatu nork deitu duen!",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena. \n-Ezetz asmatu nork deitu duen! da zuzena. ",
	"eranfb2":"Ez da zuzena. \n-Ezetz asmatu nork deitu duen! da zuzena. ",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Ezetz asmatu nork deitu duen!"},
		//......30
	{"galdera":" ¡A mí precisamente me tenía que tocar!",
	"auke1":"Zer ile luzeagoa daukazula!","auke2":"Nori eta niri tokatu behar!","auke3":"Zer ile oso luzea daukazula!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena. \n-Nori eta niri tokatu behar! da zuzena. \n-Nori tokatuko eta niri! ere zuzena da.",
	"eranfb2":"Bai, hori da erantzun zuzena: \n-Nori eta niri tokatu behar! \n-Nori tokatuko eta niri! ere zuzena da.",
	"eranfb3":"Ez da zuzena. \n-Nori eta niri tokatu behar! da zuzena. \n-Nori tokatuko eta niri! ere zuzena da."},
			//......31
	{"galdera":"¡Qué pelo más largo tienes!",
	"auke1":"Zer ile luzeagoa daukazula!","auke2":"Hori ile luzea daukazuna!","auke3":"Zer ile oso luzea daukazula!",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena. –Hori ile luzea daukazuna!–, -Bai ile luzea daukazula- eta –Zeinen ile luzea daukazun- dira zuzenak.",
	"eranfb2":"Bai, hori da erantzun zuzena.",
	"eranfb3":"Ez da zuzena. –Hori ile luzea daukazuna!–, -Bai ile luzea daukazula- eta –Zeinen ile luzea daukazun- dira zuzenak."},
	
	
	] };
	
	return galdesorta;
}
